"""
AFS (Anomaly-aware Feature Selection) adapted for CKAAD.

Adapted from RealNet (CVPR 2024).
Original: uses SDAS + Backbone to generate real anomaly features + structure blocks.
This version: uses PerlinAnomalyGenerator in feature space + PFE + simple per-layer selection.

Core idea:
1. Generate synthetic anomaly features via PerlinAnomalyGenerator on PFE output
2. For each channel, compute |anomaly - normal|^2 residual
3. Compute MSE between normalized residual and GT mask
4. Select channels with smallest MSE (most discriminative)
5. All subsequent modules use only selected channels
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from tqdm import tqdm


class AFS_Adapted(nn.Module):
    """
    Anomaly-aware Feature Selection adapted for CKAAD.

    Selects the most discriminative channels from each PFE feature layer
    based on synthetic anomaly data generated by PerlinAnomalyGenerator.

    Args:
        in_channels_list: actual input channel counts from PFE (with expansion),
                          e.g. [512, 1024] for wide_resnet50_2 layers=[2,3]
        select_planes_list: actual output channel counts to keep (with expansion),
                            e.g. [256, 512]
    """

    def __init__(self, in_channels_list, select_planes_list, selection_strategy='anomaly'):
        super(AFS_Adapted, self).__init__()

        assert len(in_channels_list) == len(select_planes_list), \
            f"in_channels_list ({len(in_channels_list)}) and " \
            f"select_planes_list ({len(select_planes_list)}) must have same length"
        if selection_strategy not in ['anomaly', 'random', 'fixed']:
            raise ValueError(
                "selection_strategy must be in ['anomaly', 'random', 'fixed'], "
                f"got {selection_strategy}"
            )

        self.num_layers = len(in_channels_list)
        self.in_channels_list = in_channels_list
        self.select_planes_list = select_planes_list
        self.selection_strategy = selection_strategy

        # Non-trainable parameters storing selected channel indices per layer
        self.indexes = nn.ParameterDict()
        for i in range(self.num_layers):
            self.indexes[f"layer_{i}"] = nn.Parameter(
                torch.zeros(select_planes_list[i], dtype=torch.long),
                requires_grad=False
            )

    @torch.no_grad()
    def forward(self, features):
        """
        Select channels from each feature layer.

        Args:
            features: list of [B, Ci, Hi, Wi] tensors from PFE

        Returns:
            list of [B, Si, Hi, Wi] tensors with selected channels (Si <= Ci)
        """
        selected = []
        for i, feat in enumerate(features):
            idx = self.indexes[f"layer_{i}"].data
            if idx.numel() > 0 and idx.max() < feat.size(1):
                feat_c = torch.index_select(feat, 1, idx)
            else:
                # Fallback: use first n channels if indices not initialized
                feat_c = feat[:, :self.select_planes_list[i], :, :]
            selected.append(feat_c)
        return selected

    @torch.no_grad()
    def init_idxs(self, pfe, perlin_gen, dataloader, init_bsn, device):
        """
        Initialize channel selection indices using synthetic anomalies.

        Process:
        1. Normal features from PFE(normal_img)
        2. Synthetic anomaly features via PerlinAnomalyGenerator on normal features
        3. Per-channel residual: |anomaly - normal|^2
        4. Normalize each channel's residual to [0, 1]
        5. MSE between normalized residual and GT mask
        6. Select channels with smallest MSE (most discriminative for anomaly)

        Args:
            pfe: PretrainedFeatureExtractor (frozen, eval mode)
            perlin_gen: PerlinAnomalyGenerator instance
            dataloader: DataLoader yielding normal image batches
            init_bsn: number of batches for initialization
            device: torch device
        """
        if self.selection_strategy == 'fixed':
            for i in range(self.num_layers):
                k = min(self.select_planes_list[i], self.in_channels_list[i])
                self.indexes[f"layer_{i}"].data.copy_(
                    torch.arange(k, device=device, dtype=torch.long)
                )
            return

        if self.selection_strategy == 'random':
            for i in range(self.num_layers):
                k = min(self.select_planes_list[i], self.in_channels_list[i])
                indices = torch.randperm(self.in_channels_list[i], device=device)[:k]
                indices, _ = torch.sort(indices)
                self.indexes[f"layer_{i}"].data.copy_(indices.long())
            return

        pfe.eval()

        # Per-channel MSE loss bank: cumulative MSE per channel per layer
        cri_sum_vec = [torch.zeros(self.in_channels_list[i]).to(device)
                       for i in range(self.num_layers)]

        iterator = iter(dataloader)

        pbar = tqdm(range(init_bsn), desc="Initializing AFS indices")
        for _ in pbar:
            try:
                batch = next(iterator)
            except StopIteration:
                iterator = iter(dataloader)
                batch = next(iterator)

            normal_img = batch[0].to(device)

            # 1. Extract PFE features
            normal_feats = pfe(normal_img)  # list of [B, Ci, Hi, Wi]

            # 2. Generate synthetic anomaly features + masks
            #    PerlinAnomalyGenerator returns (anomaly_feats, masks_list)
            #    each matching normal_feats shapes
            anomaly_feats, masks = perlin_gen(normal_feats)

            # 3. For each feature layer
            for i, (ano_feat, nor_feat, mask) in enumerate(zip(
                    anomaly_feats, normal_feats, masks)):

                C = ano_feat.size(1)

                # Per-channel MSE residual: |anomaly - normal|^2
                layer_residual = (ano_feat - nor_feat) ** 2  # [B, C, H, W]

                # Normalize each channel to [0, 1]
                # Reshape: [C, B*H*W]
                residual_flat = layer_residual.permute(1, 0, 2, 3).contiguous().view(C, -1)

                min_vals, _ = torch.min(residual_flat, dim=1)
                max_vals, _ = torch.max(residual_flat, dim=1)
                range_vals = max_vals - min_vals + 1e-8
                residual_norm = (residual_flat - min_vals.unsqueeze(1)) / range_vals.unsqueeze(1)

                # GT mask → same shape as normalized residual
                label = mask.permute(1, 0, 2, 3).contiguous().view(1, -1).repeat(C, 1)

                # MSE: mean((pred - mask)^2) per channel → [C]
                mse_loss = torch.mean((residual_norm - label) ** 2, dim=1)

                cri_sum_vec[i] += mse_loss

        # Select k channels with smallest loss (most discriminative)
        for i in range(self.num_layers):
            # Handle NaN
            if torch.isnan(cri_sum_vec[i]).any():
                max_valid = torch.max(cri_sum_vec[i][~torch.isnan(cri_sum_vec[i])])
                cri_sum_vec[i][torch.isnan(cri_sum_vec[i])] = max_valid

            k = min(self.select_planes_list[i], cri_sum_vec[i].size(0))
            _, indices = torch.topk(cri_sum_vec[i], k=k, dim=-1, largest=False)
            indices, _ = torch.sort(indices)

            self.indexes[f"layer_{i}"].data.copy_(indices.long())
            pbar.write(
                f"AFS layer_{i}: selected {k}/{self.in_channels_list[i]} channels"
            )

        pbar.close()
