import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Optional


class ConvBlock(nn.Module):
    """
    Basic Conv-BN-ReLU block.
    """
    def __init__(self, in_channels: int, out_channels: int, kernel_size: int = 3):
        super().__init__()
        padding = kernel_size // 2
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, padding=padding, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class ErrorReliabilityModulation(nn.Module):
    """
    Energy-guided Error Reliability Modulation (EERM) module.

    This module is designed as a plug-in head on top of an existing CKAAD model.
    It does NOT replace the original anomaly candidate generation.
    Instead, it takes the original reconstruction error map and several auxiliary
    cues, then predicts a pixel-wise reliability gate to suppress false positives.

    Mathematical form:
        W = sigmoid(phi([Err, Energy, Delta_1, Delta_2, ...]))
        Refined = Err * W

    Expected inputs:
        base_error_map: [B, 1, H, W]
            Original anomaly candidate map generated by CKAAD.

        energy_map: [B, 1, H, W]
            Energy map from energy discriminator. If not already 1-channel, you should
            project it before feeding it here.

        extra_maps: Optional[List[Tensor]]
            Additional discrepancy variables. Each tensor should have shape [B, C_i, H, W].
            For example:
                - abs(feature - recon_feature) reduced to 1-channel
                - abs(base_error_map - normalized_energy_map)
                - other hand-crafted discrepancy cues

    Outputs:
        Dict with keys:
            "weight_map":   [B, 1, H, W]
            "refined_map":  [B, 1, H, W]
            "norm_energy":  [B, 1, H, W]
    """

    def __init__(
        self,
        extra_channels: int = 0,
        hidden_channels: int = 32,
        use_batchnorm: bool = True
    ):
        super().__init__()

        # Input channels:
        #   1 for base_error_map
        #   1 for energy_map
        #   extra_channels for user-defined discrepancy maps
        in_channels = 2 + extra_channels

        if use_batchnorm:
            self.fusion_net = nn.Sequential(
                ConvBlock(in_channels, hidden_channels, kernel_size=3),
                ConvBlock(hidden_channels, hidden_channels, kernel_size=3),
                nn.Conv2d(hidden_channels, 1, kernel_size=1, padding=0, bias=True)
            )
        else:
            self.fusion_net = nn.Sequential(
                nn.Conv2d(in_channels, hidden_channels, kernel_size=3, padding=1),
                nn.ReLU(inplace=True),
                nn.Conv2d(hidden_channels, hidden_channels, kernel_size=3, padding=1),
                nn.ReLU(inplace=True),
                nn.Conv2d(hidden_channels, 1, kernel_size=1, padding=0)
            )

    @staticmethod
    def minmax_normalize(x: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
        """
        Per-sample min-max normalization for a [B, C, H, W] tensor.
        Usually used for energy map normalization.
        """
        b = x.shape[0]
        x_flat = x.view(b, -1)
        x_min = x_flat.min(dim=1, keepdim=True)[0].view(b, 1, 1, 1)
        x_max = x_flat.max(dim=1, keepdim=True)[0].view(b, 1, 1, 1)
        x_norm = (x - x_min) / (x_max - x_min + eps)
        return x_norm

    @staticmethod
    def topk_mean(x: torch.Tensor, k_ratio: float = 0.01) -> torch.Tensor:
        """
        Compute per-sample mean of top-k values on [B, 1, H, W].
        Return shape: [B]
        """
        assert x.dim() == 4 and x.shape[1] == 1, "Input must be [B, 1, H, W]"
        b, _, h, w = x.shape
        n = h * w
        k = max(1, int(n * k_ratio))
        x_flat = x.view(b, -1)
        topk_vals = torch.topk(x_flat, k=k, dim=1, largest=True, sorted=False)[0]
        return topk_vals.mean(dim=1)

    @staticmethod
    def reduce_feature_diff_to_map(feat: torch.Tensor, recon_feat: torch.Tensor, mode: str = "l1") -> torch.Tensor:
        """
        Convert feature-level discrepancy [B, C, H, W] into a single-channel map [B, 1, H, W].

        mode:
            - "l1": mean absolute difference over channel dimension
            - "l2": mean squared difference over channel dimension
            - "cos": 1 - cosine similarity over channel dimension
        """
        assert feat.shape == recon_feat.shape, "feat and recon_feat must have the same shape"

        if mode == "l1":
            return torch.mean(torch.abs(feat - recon_feat), dim=1, keepdim=True)
        elif mode == "l2":
            return torch.mean((feat - recon_feat) ** 2, dim=1, keepdim=True)
        elif mode == "cos":
            feat_n = F.normalize(feat, dim=1)
            recon_n = F.normalize(recon_feat, dim=1)
            cos_sim = torch.sum(feat_n * recon_n, dim=1, keepdim=True)
            return 1.0 - cos_sim
        else:
            raise ValueError(f"Unsupported mode: {mode}")

    def forward(
        self,
        base_error_map: torch.Tensor,
        energy_map: torch.Tensor,
        extra_maps: Optional[List[torch.Tensor]] = None
    ) -> Dict[str, torch.Tensor]:
        """
        Forward pass.

        Args:
            base_error_map: [B, 1, H, W]
            energy_map:     [B, 1, H, W]
            extra_maps:     optional list of maps, each [B, C_i, H, W]

        Returns:
            {
                "weight_map":  [B, 1, H, W],
                "refined_map": [B, 1, H, W],
                "norm_energy": [B, 1, H, W],
            }
        """
        assert base_error_map.dim() == 4 and base_error_map.shape[1] == 1, \
            "base_error_map must be [B, 1, H, W]"
        assert energy_map.dim() == 4 and energy_map.shape[1] == 1, \
            "energy_map must be [B, 1, H, W]"

        norm_energy = self.minmax_normalize(energy_map)

        fusion_inputs = [base_error_map, norm_energy]

        if extra_maps is not None:
            for extra in extra_maps:
                assert extra.dim() == 4, "Each extra map must be 4D [B, C, H, W]"
                assert extra.shape[0] == base_error_map.shape[0], "Batch size mismatch"
                assert extra.shape[2:] == base_error_map.shape[2:], "Spatial size mismatch"
                fusion_inputs.append(extra)

        x = torch.cat(fusion_inputs, dim=1)
        weight_logits = self.fusion_net(x)
        weight_map = torch.sigmoid(weight_logits)

        refined_map = base_error_map * weight_map

        return {
            "weight_map": weight_map,
            "refined_map": refined_map,
            "norm_energy": norm_energy
        }

    def loss_good(self, refined_map: torch.Tensor) -> torch.Tensor:
        """
        Good-sample suppression loss:
            L_good = mean(refined_map)

        Used on normal samples to suppress false positives.
        """
        return refined_map.mean()

    def loss_keep(
        self,
        refined_map: torch.Tensor,
        base_error_map: torch.Tensor,
        tau: float = 0.7,
        k_ratio: float = 0.01,
        eps: float = 1e-6
    ) -> torch.Tensor:
        """
        Peak-retention loss:
            L_keep = mean( max(0, tau - TopK(refined) / (TopK(base) + eps)) )

        This prevents the refinement module from suppressing true anomaly peaks too much.
        Used on anomalous samples.

        Args:
            refined_map:    [B, 1, H, W]
            base_error_map: [B, 1, H, W]
            tau: desired minimum peak-retention ratio
            k_ratio: top-k ratio for computing the strongest anomaly responses
        """
        refined_topk = self.topk_mean(refined_map, k_ratio=k_ratio)   # [B]
        base_topk = self.topk_mean(base_error_map, k_ratio=k_ratio)   # [B]

        ratio = refined_topk / (base_topk + eps)
        loss = F.relu(tau - ratio).mean()
        return loss

    def compute_modulation_loss(
        self,
        refined_map: torch.Tensor,
        base_error_map: torch.Tensor,
        is_normal: torch.Tensor,
        lambda_good: float = 1.0,
        lambda_keep: float = 1.0,
        tau: float = 0.7,
        k_ratio: float = 0.01
    ) -> Dict[str, torch.Tensor]:
        """
        Compute modulation loss for mixed batches.

        Args:
            refined_map:    [B, 1, H, W]
            base_error_map: [B, 1, H, W]
            is_normal:      [B], tensor of 0/1 or bool
                            1 means normal sample
                            0 means anomalous sample

        Loss:
            L_mod = lambda_good * L_good + lambda_keep * L_keep

        For normal samples:
            use refined_map.mean()

        For anomalous samples:
            use peak-retention constraint

        Returns:
            {
                "loss_mod": total scalar,
                "loss_good": scalar,
                "loss_keep": scalar
            }
        """
        if is_normal.dtype != torch.bool:
            is_normal = is_normal > 0

        normal_mask = is_normal
        anomaly_mask = ~is_normal

        loss_good = refined_map.new_tensor(0.0)
        loss_keep = refined_map.new_tensor(0.0)

        if normal_mask.any():
            loss_good = self.loss_good(refined_map[normal_mask])

        if anomaly_mask.any():
            loss_keep = self.loss_keep(
                refined_map=refined_map[anomaly_mask],
                base_error_map=base_error_map[anomaly_mask],
                tau=tau,
                k_ratio=k_ratio
            )

        loss_mod = lambda_good * loss_good + lambda_keep * loss_keep

        return {
            "loss_mod": loss_mod,
            "loss_good": loss_good.detach(),
            "loss_keep": loss_keep.detach()
        }